POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_ric0",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_ri",
  "name": "Adam Richard",
  "password": "ri",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_rd0",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}





###
Post http://localhost:3000/login/
Content-Type: application/json

{
  "username": "adam_rard0",
  "password": "richard_567"
}

###

PUT  http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}